version: '3'

services:
  db:
    image: mysql
    restart: always
    container_name: database_container
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data/db_data:/var/lib/mysql

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress_container
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./data/wordpress_data:/var/www/html
    ports:
      - 80:80
volumes:
  db_data:
  wordpress_data: